### PR TITLE
Add support for output from STAR-fusion 1.10

### PR DESCRIPTION
**Pull request by Redmar-van-den-Berg**

### CODE REVIEW

**Comment by bow** [comment]
LGTM :+1: ~ thanks @Redmar-van-den-Berg, merging now.

**Comment by Redmar-van-den-Berg** [comment]
Thanks for merging! I would like to get this version of crimson into the latest fsnviz, could you make a new (minor) release of crimson and put that on pypi? I'm maintainer of fsnviz on pypi, so I can publish a new minor release of fsnviz there.

**Comment by bow** [comment]
Hey @Redmar-van-den-Berg ~ sure thing. I'll do a release later tonight and ping back here again :slightly_smiling_face:.

**Comment by bow** [comment]
And to close this off, Crimson 1.1.0 is now available via PyPI: https://pypi.org/project/crimson/1.1.0/.

**Pull request merged**
